services:
  api:
    build:
      context: ./api
    container_name: pokemath-api
    volumes:
      - /var/lib/pokemath:/var/lib/pokemath
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.api-strip.stripprefix.prefixes=/api"
      - "traefik.http.routers.api.middlewares=api-strip"
      - "traefik.http.services.api.loadbalancer.server.port=3000"
    networks:
      - web-traffic

  web:
    build:
      context: ./web
    container_name: pokemath-web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.priority=1"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
    networks:
      - web-traffic
