services:
  traefik:
    image: traefik:v3.6
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - web-traffic

  api:
    build:
      context: ./api
      target: dev
    container_name: pokemath-api
    volumes:
      - /var/lib/pokemath:/var/lib/pokemath
    environment:
      - NODE_ENV=development
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`localhost`) && PathPrefix(`/api`)"
      - "traefik.http.middlewares.api-strip.stripprefix.prefixes=/api"
      - "traefik.http.routers.api.middlewares=api-strip"
      - "traefik.http.services.api.loadbalancer.server.port=3000"
    develop:
      watch:
        - path: ./api/src
          action: sync
          target: /usr/local/app/src
        - path: ./package.json
          action: rebuild
    networks:
      - web-traffic

  web:
    build:
      context: ./web
      target: dev
    container_name: pokemath-web
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://127.0.0.1:80/api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`localhost`)"
      - "traefik.http.routers.frontend.priority=1"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
    develop:
      watch:
        - path: ./web/src
          action: sync
          target: /usr/local/app/src
        - path: ./package.json
          action: rebuild
    networks:
      - web-traffic

networks:
  web-traffic:
    driver: bridge
    name: web-traffic
